{
  "dataset_name": "TokenBender/roleplay_raw_text",
  "model_name": "Gryphe/MythoLogic-L2-13b",
  "bnb_config": {
    "load_in_4bit": true,
    "bnb_4bit_quant_type": "nf4",
    "bnb_4bit_compute_dtype": "torch.bfloat16"
  },
  "lora_config": {
    "lora_alpha": 16,
    "lora_dropout": 0.1,
    "lora_r": 64,
    "bias": "none",
    "task_type": "CAUSAL_LM"
  },
  "training_args": {
    "output_dir": "./results",
    "per_device_train_batch_size": 12,
    "gradient_accumulation_steps": 8,
    "optim": "paged_adamw_32bit",
    "save_steps": 100,
    "logging_steps": 1,
    "learning_rate": 0.0002,
    "fp16": true,
    "max_grad_norm": 0.3,
    "max_steps": -1,
    "warmup_ratio": 0.03,
    "group_by_length": true,
    "lr_scheduler_type": "cosine",
    "weight_decay": 0.0,
    "num_train_epochs": 1
  },
  "max_seq_length": 2048,
  "push_to_hub": {
    "enabled": true,
    "model_name": "AggressiveChameli_13B"
  },
  "wandb_project_name": "AggressiveChameli_13B",
  "wandb_run_name": "qlora"
}
